#! /bin/bash
echo 'Git commit successful. Running test suite'
homedir=$(git rev-parse --show-toplevel)
cd $homedir
#python3 -m test.test_csv
#echo 'Test suite ended'


echo '============================= Running Code Coverage =========================\n'
coverage run -m test.test_csv
echo $(coverage report -m)

echo 'Test suite ended'
echo '============================ End of coverage report =========================\n'


cd docs
python -m pydoc -w ../src/*
echo 'Regenerated documentation'