language: python
python:
  - "3.8"
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
script:
  coverage run -m test.test_csv
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 034dc4a3-0afb-4961-92c1-182ba3c6dc5b
